### ISSUE TITLE
Unequal 'time' points across cores

### ISSUE THREAD

**Issue by andydawson** [SimonGoring/NonAnalogues#10]
I've been thinking about how to include temporal correlation structure into the model. In the flow chart, we were thinking about t_n = f(t_(n-1)). Originally when I was thinking about it, I was thinking that t_n would be the dissimilarity measurements for all cores at time n, and that those would be lognormal (or gamma). But we never actually have very many samples for any individual time point, which makes this a bit harder than I thought. Or maybe I am missing something - were you thinking in discrete or continuous time?

Also, do you expect the temporal correlation to change much between cores? For something like tree rings, I would expect  this the temporal correlation to be somewhat constant, at least for tree of a given species growing in close proximity. But for tree rings we get measurements at each year so it is easier to use an autoregressive model to introduce this temporal correlation structure.

Still thinking....

**Comment by SimonGoring** [comment]
For any core m we have a set of unique, continuous time points (i) that may or may not be shared by other cores.  Right now we are not binning ages and the ages have no uncertainty (they're pulled right from Neotoma).  We could also bin.  Blois et al. (2011) makes the case for a 500 year window, my feeling was to use the continuous ages now, but do the estimation of trends at a 500 year bin (use the raw data until we need to present results).

We then have multiple distance measures, for now we can define them as:
1. d<sub>s, m, i</sub> (sorry if this isn't proper notation): Distance to another assemblage within the core between 250 and 750 years prior to A<sub>mi</sub>, where A<sub>mi</sub> is  a pollen assemblage in core m at age i.
2.  d<sub>l, m, i</sub>: Distance to another assemblage from the landscape of pollen assemblages (excluding the core) between 250 and 750 years prior to A<sub>mi</sub>.
3.  d<sub>b, m, i</sub>: Not sure if we need this, but this is the mean minimum distance for all samples between 250 and 750 years prior to A<sub>mi</sub> estimated by bootstrapping with replacement 1000 times.  Part of my thinking here is that it might help to account for issues of sample density, particularly earlier in the core.

Temporal correlation probably does change within cores.  I would assume a core in a grassland has a much lower temporal autocorrelation with regards to vegetation than a woodland record, so, at the largest extremes we would expect a site that shifts from grassland to woodland, or _vice versa_ to show rapid shifts in temporal autocorrelation.  What doesn't change is the temporal distance from a sample to the samples from which we test dissimilarity.  It's always a window of between 250 and 750 years.

We could actually plot a histogram of where the minimum samples are being found though, if it was skewed left then we'd know that older samples were being taken preferentially (maybe the temporal resolution of the record was really low?), whereas if it was skewed right then we'd know that minimum dissimilarites were always coming from more recent samples, and so we'd maybe have to adjust our sampling window.

Super long answer, sorry :)  Does it answer any of the points you were trying to make?

**Comment by SimonGoring** [comment]
Deprecating project, closing issues.
