### ISSUE TITLE
Minimums and their spatial distribution

### ISSUE THREAD

**Issue by SimonGoring** [SimonGoring/NonAnalogues#9]
If we record where the minimum points are found, we might expect that during the late-Glacial, early Holocene they are found to the south, and then in the most recent past, there would be no geographic trend.

We can test this as a hypothesis.

**Comment by SimonGoring** [comment]
It requires not only identifying the minima, but also the spatial location of the minima relative to the point in question.

**Comment by SimonGoring** [comment]
Is it worth it?  We would have to re-code the distance section, and we'd have to decide how we were going to do distances in the bootstrap estimates.

**Comment by andydawson** [comment]
I think it's worth it. What would be really interesting would be to plot dissimilarity (d_s and d_l) against distance by core. Are closer sites more similar in general? I think we would expect that they would be because of the spatial correlation, but this would be a great check.

**Comment by SimonGoring** [comment]
Deprecating project, closing issues.
